### ISSUE TITLE
No simple processor?

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#216]
In Python, I can use `BatchExportSpanProcessor` for long running processes and `SimpleExportSpanProcessor` when I need synchronous delivery. I'm tempted to do the latter in my tests for Elixir integrations, but `opentelemetry` literally won't launch if it doesn't have an `otel_batch_processor` to play with.

**Comment by tsloughter** [comment]
So yea, I didn't implement the simple processor as it didn't seem needed since it still wouldn't be synchronous. It calls the same form of exporter so it still needs to serialize all spans through a single process that calls the exporter. The difference is the batch size would be 1.

So I saw it more as a configuration of our batch processor. I could be wrong, and am open to adding it if I am.

**Comment by tsloughter** [comment]
I can't remember why I thought it couldn't be synchronous...

We should add the simple processor if it can be synchronous.

My only worry then is making sure it isn't accidentally used by a user who doesn't have a need for this and ends up having shit performance.

**Comment by tsloughter** [comment]
Simple processor has been added recently soc losing this issue. Thanks!
