### ISSUE TITLE
Take attributes as map

### ISSUE THREAD

**Issue by garthk** [open-telemetry/opentelemetry-erlang#231]
I'd like to have the Elixir side, at least, of the API take attributes as a map with binary keys to match the `opentelemetry:attribute_value` type and, given how #224 is headed, the baggage. Given both, I'll be able to copy baggage to attributes without surprising anyone:

```elixir
OpenTelemetry.Tracer.set_attributes(OpenTelemetry.Baggage.get_all())
```

I can do the lifting, just want to prod discussion in case I'm out of line. @ferd? @tsloughter?

**Comment by ferd** [comment]
Sorry, I've been out of it. I'm not sure I fully get the request.  The `attribute_value()` type is `any()` so I'm not sure what type matching there's there, unless you meant `attributes()` which should be `[{attribute_key() :: atom() | binary(), attribute_value() :: any()}]`. 

I'm not sure what you mean by "attributes as a map with binary keys to match the [...] type" since the type is neither a map nor restricted to binary keys. I don't necessarily see an issue in submitting maps, but be aware that there are semantic differences between a list and a map:

- map items have no defined order but lists do
- lists support duplicate keys with different (or repeated) values, and maps do not

As such, lists are a superset of maps in what they support, which means that _if_ we accept maps when setting attributes, we should nevertheless convert them to a list as soon as possible to change none of the semantics.

**Comment by garthk** [comment]
Sorry, yes, I was hoping to have `attributes` support a map from `attribute_key` to `attribute_value` as an alternative to a list of `{attribute_key, attribute_value}` tuples; only at the point of starting a span or adding attributes; and only in the Elixir API.

Speaking of the underlying semantics, though: I'd expected OT span attributes to have map semantics, so even if we were using a list to carry them to the exporter I'd expect only a single value for any key out the other end? Perhaps I'm up for a surprise, there… \[checks] the Python `attributes` is a dict, as I expected, but the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes) says only that attributes are a list of zero or more key-value pairs. It spends a chunky paragraph talking about `null`, but doesn't cover duplicate keys at all. The protobuf [definition](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L161) says it's a repeated `KeyValue` which is still very listy… aah here's a hint in the spec on how to [Set Attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-attributes):

> Setting an attribute with the same key as an existing attribute SHOULD overwrite the existing attribute's value.

Strikes me we SHOULD convert keys to binary and then eliminate duplicates, at the time that we set attributes, even if we retain a list as the way we're carrying it?

**Comment by bryannaegele** [comment]
> as an alternative to a list of {attribute_key, attribute_value} tuples

Using atom keys, this is just a keyword list in Elixir. It's only necessary to provide tuples if not using atoms for the key.

> Strikes me we SHOULD convert keys to binary and then eliminate duplicates

Binary keys are very memory intensive which is why we support atoms and only convert them on export.

Any deduplication would have to happen in the implementation of `set_attribute(s)`, but I'm not sure we'd want to try to box/unbox atoms to binaries every time we do that just to try to catch that edge case.

**Comment by tsloughter** [comment]
Just to ad done point on top of @bryannaegele 's good points, we store the attributes as a list in ETS which means doing the de-duplication later we get the same result as if we did it at the time they were added.

**Comment by bryannaegele** [comment]
> doing the de-duplication later we get the same result

The one minor thing there is we currently prepend to the list when adding a single attribute and append when it's multiple, so we'd have to make those consistent.

But yeah, a proplist to map automatically dedupes keys and uses the last one provided in the list, so the exporter is capable of this with just boxing and unboxing the list with a map before we process the attribute list.

**Comment by tsloughter** [comment]
Oh dammit, I must have done that as an optimization.

**Comment by bryannaegele** [comment]
This discussion came back to mind with the limiting attribute counts for 1.0 and I saw we hadn't fixed [this](https://github.com/open-telemetry/opentelemetry-erlang/issues/231#issuecomment-817142897) yet.

I think there's a case to be made for changing attribute storage to maps. Since the point of the limits is to prevent exhausting memory, it seems like this should be done at the time the attributes (and events, links, etc) are added rather than at export.

When adding limits, we have [this clause](https://github.com/open-telemetry/opentelemetry-specification/blob/e2c2472985b17e37a25a7dc5aa0aa071e6683c98/specification/common/common.md#attribute-limits) from the spec where the limits are based on unique keys and we must drop them. I think we're also supposed to replace the value on an existing key, so de-duplicating later is also problematic since we have to track the number of unique keys. `map_size/1` is probably efficient enough.

**Comment by tsloughter** [comment]
Yea, you are right.

**Comment by bryannaegele** [comment]
Implemented in rc4
