### ISSUE TITLE
Add a badge for Code Coverage

### ISSUE THREAD

**Issue by xyira** [open-telemetry/opentelemetry-erlang#249]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for code coverage. In an effort to have the Erlang SDK repository to be up to date and consistent with the other established SDKs and repositories, there should be a code coverage badge in the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a code coverage percentage badge at the top of the README document of the Erlang repo. Code coverage badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding a code coverage badge to the README.md, with a quick scan, any observer will be able to know the status of the repository.

cc: @alolita

**Comment by tsloughter** [comment]
Yes, we should and will get it added. There is some complication with our coverage % because of the repo and tests actually existing across 2 languages (Erlang and Elixir) and I don't know that there is a way to merge the coverage so that the correct % is shown. Right now it will show an inaccurate and low % because of this issue so I wasn't wanting to put it in the readme.
