### ISSUE TITLE
values in event can not be complex types

### ISSUE THREAD

**Issue by RoadRunnr** [open-telemetry/opentelemetry-erlang#276]
The typespec for `attribute_value` says it can have `any` value:

```
-type attribute_value()    :: any().
```

The code in apps/opentelemetry_exporter/src/opentelemetry_exporter.erl to_attributes function seems to support that.

However, when inspecting the final protobuf message, it turns out that complex types like maps, tuples and lists are not exported.

e.g. this:

```
    ?add_event(<<"complex_ev_map">>, [{map, #{entry => 1}}]),
```

ends up in the trace as (when decoded with protoc):

```
      events {
        time_unix_nano: 1631787808257319367
        name: "complex_ev"
        attributes {
          key: "map"
        }
      }
```

Other constructs completely break the export:

```
    ?add_event(<<"complex_ev_list">>, [{list, [list]}]),
```

will result in not trace whatsoever.

**Comment by tsloughter** [comment]
Definitely some bug here but to start, you shouldn't put the type in the attributes. I believe you are basing the way you add attributes, like `{map, #{entry => 1}}` on what is in the proto? The exporter adds the type information when constructing the proto, adding it when you are in these code samples changes the attribute value to be something  you don't want.

Now that I type this I'm not sure there is a bug except that `any()` isn't technically accurate. I don't believe nested complex data is supported and because your values are tuples with maps or lists in them as the second element this is nested complex data.

Does it work if you instead do : `?add_event(<<"complex_ev_map">>, [#{entry => 1}]),`

**Comment by RoadRunnr** [comment]
You are probably right with `any()` being wrong.

According to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes, the values can only be:

>* A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.
> * An array of primitive type values. The array MUST be homogeneous, i.e. it MUST NOT contain values of different types. For protocols that do not natively support array values such values SHOULD be represented as JSON strings.

**Comment by tsloughter** [comment]
I think the intention behind `any()` was that we can turn any Erlang term into a string, so we can accept anything and if it isn't a support type turn it into a string.

We should likely restrict this to like atoms which are useful for users to be able to pass and not have to convert to strings themselves, and being stored as an atom until export helps with memory pressure.

**Comment by tsloughter** [comment]
Closing because I think this was all cleared up in the 1.0 release. Please re-open if this isn't the case.
