### ISSUE TITLE
Erlang.mk users have to patch OpenTelemetry-api because it uses rebar file version 

### ISSUE THREAD

**Issue by josephDunne** [open-telemetry/opentelemetry-erlang#295]
Hey, thank you for the awesome project. If you want to use OpenTelemetry on an Erlang.mk project we have to add a dependency on opentelemetry-api and then patch the app.src otherwise the build fails because erlang.mk does not support the rebar file vsn plugin. Is there a specific reason the api is using a VERSION file and the other apps are using git for the vsn? 

Example patch:
```Makefil
autopatch-opentelemetry_api::
	patch $(DEPS_DIR)/opentelemetry_api/src/opentelemetry_api.app.src < opentelemetry.patch
```
and the patch file:
```patch
3c3
<               {vsn,{file,"VERSION"}},
---
>               {vsn,"1.0.0.rc.2"},
```

**Comment by tsloughter** [comment]
I think the reason was so the `mix.exs` file could read it too, but now that looks to first go to `.app.src` to get the `vsn`. The version isn't always the same between the SDK and API so the tag can't be used for both. But if there isn't a reason for it now that `mix.exs` reads and parses `.app.src` we may be able to just put the version string in `vsn`.

Might always want to propose support in erlang.mk.

**Comment by tsloughter** [comment]
This was resolved.
