### ISSUE TITLE
tls_certificate_check is not started

### ISSUE THREAD

**Issue by ruslandoga** [open-telemetry/opentelemetry-erlang#419]
👋

I'm getting a warning

```
 14:13:22.924 [warning] OTLP exporter failed to initialize with exception :throw:{:application_either_not_started_or_not_ready, :tls_certificate_check}
```

when using `:opentelemetry` in an Elixir project. It doesn't seem to affect much, but I wonder if `tls_certificate_check` needs to be added to [`:applications`](https://github.com/open-telemetry/opentelemetry-erlang/blob/6990ff30ff4e36ff52ea6a352d09eabf2193a40f/apps/opentelemetry/src/opentelemetry.app.src#L6-L10) to avoid it?

**Comment by dvic** [comment]
I also ran into this. You need to add opentelemetry_exporter before your other opentelemetry dependencies in mix.exs so that it starts before opentelemetry does.

For mix releases you also need some configuration (see readme for details).

**Comment by dvic** [comment]
See also https://github.com/open-telemetry/opentelemetry-erlang/commit/da81eb0b602a93a47f4c4b1220e06080b6682779

**Comment by ruslandoga** [comment]
@dvic I don't think it solves the issue as it shouldn't matter in what order I have dependencies in `mix.exs`. The inter-dependencies should be resolved at opentelemetry level.

**Comment by dvic** [comment]
> @dvic Thank you for the info! But I don't think it solves the issue as it shouldn't matter in what order I have dependencies listed in `mix.exs`. The inter-dependencies should be resolved and properly started at `:opentelemetry` level.

I agree it's less than ideal but, if I recall correctly, the `opentelemetry_exporter` is pluggable so `:opentelemetry` can't depend on it. But maybe it could start it? This issue became a thing when #387 got merged I think, but maybe @tsloughter can chime in on that.

**Comment by ruslandoga** [comment]
#387 seems to be about removing `:opentelemetry` from `:opentelemetry_exporter` deps, which is not what seems to be causing the issue: `:opentelemetry` not waiting for `:tls_certificate_check`.

**Comment by tsloughter** [comment]
Correct @dvic, `opentelemetry` can't depend on `opentelemetry_exporter` because there are other exporters besides OTLP.

I'd be open to adding `opentelemetry_exporter` as an optional dependency in `opentelemetry.app.src`. Technically would still be an "issue" (nothing is actually hurt by this warning, once the applications start the SDK will successfully initialize the exporter)  for third party exporters -- should actually include `opentelemetry_zipkin` as well as an optional app -- but that'd probably be acceptable to get rid of this confusion :).

But yes, putting `opentelemetry_exporter` first in the release list of applications is how you resolve this currently. This is not uncommon in OTP releases. Before `optional_applications` was added in OTP-25 this is how optional applications were dealt with.

**Comment by ruslandoga** [comment]
@tsloughter @dvic thank you both for the explanation! It makes sense now.

**Comment by grzuy** [comment]
Hey 👋 

Also seeing this warning message

```
[warning] OTLP exporter failed to initialize with exception :throw:{:application_either_not_started_or_not_ready, :tls_certificate_check}
```

After debugging and troubleshooting, this feels like a race condition, given that `opentelemetry_exporter` calls

https://github.com/open-telemetry/opentelemetry-erlang/blob/75122443cd6c89bf6bf4c593efbc4dfa76fb19da/apps/opentelemetry_exporter/src/otel_exporter_otlp.erl#L329

when the `tls_certificate_check` app is still starting and initializing the certificates list state.

ending up throwing here inside `tls_certificate_check`:

https://github.com/g-andrade/tls_certificate_check/blob/6a5e03c9288f46395cefcf2cf00a0cb039882470/src/tls_certificate_check_shared_state.erl#L471-L480

which is later caught by `opentelemetry` and just logged as a warning in

https://github.com/open-telemetry/opentelemetry-erlang/blob/75122443cd6c89bf6bf4c593efbc4dfa76fb19da/apps/opentelemetry/src/otel_exporter.erl#L58-L96

I see discussion in the thread pointing to the dependency between `opentelemetry` and `opentelemtery_exporter`, but this feels more like `opentelemetry_exporter` needed `tls_certificate_check` app to be fully started (i.e. it's ets table to be initialized).

Isn't the responsibility of `opentelemetry_exporter` to make sure `tls_certificate_check` is started and functional before calling `tls_certificate_check:options`?

**Comment by tsloughter** [comment]
Does starting `tls_certificate_check` not block until it is fully initialized? If not, and that is causing the issue, then adding a start won't fix it (though it might make it go away in some cases due to timing if its a race condition).

Maybe there is a way to block in the exporter until it is fully initialized.

I'd like to just drop the exporter as a separate dep and move it into the SDK package to get rid of these issues. Or make it a required dep of the SDK.

**Comment by tsloughter** [comment]
If I'm reading the shared state gen_server right it should block until initialized.. so confused how this is happening.

**Comment by tsloughter** [comment]
Nevermind! I was reading it wrong, I missed this https://github.com/g-andrade/tls_certificate_check/blob/6a5e03c9288f46395cefcf2cf00a0cb039882470/src/tls_certificate_check_shared_state.erl#L186

**Comment by grzuy** [comment]
> Does starting `tls_certificate_check` not block until it is fully initialized?

Yes. Seems to be the case.

> If not, and that is causing the issue, then adding a start won't fix it (though it might make it go away in some cases due to timing if its a race condition).

Yes, you're right. Good call.

> 
> Maybe there is a way to block in the exporter until it is fully initialized.

Trying to something like this.

> I'd like to just drop the exporter as a separate dep and move it into the SDK package to get rid of these issues. Or make it a required dep of the SDK.

**Comment by g-andrade** [comment]
`tls_certificate_check` 1.30.0 works around these early calls by ensuring that the app is started if the shared state is not there (or awaiting on the gen server if it's still initializing). Not the most elegant fix, but it should reduce friction.
